### ISSUE TITLE
the arrangement of the crystal indices and the arrangement of tof-bins in the sinogram

### ISSUE THREAD

**Issue by zjutk** [gschramm/pyparallelproj#1]
My first question is regarding the arrangement of the crystal indices generated by the function `get_view_crystal_indices` in sinogram.py. As written in your code, the range of indices for `i_tr_start` goes from 224 to -224, and for `i_tr_end` from -1 to -450, without trimming. Could you please clarify what the negative sign represents in these crystal indices? May I interpret it as follows: if the positive indices represent the crystals arranged clockwise starting from 0, then do the negative indices signify a counterclockwise arrangement, with the possibility of a crystal being represented by both a positive and a negative index (for example, crystal 1 = -447)?

My second question pertains to the arrangement of tof-bins in the sinogram generated by `joseph3d_fwd_tof_sino` in projectors.py. Theoretically, the shape of the projected sinogram should be (nradial, nviews, nplanes, ntofbins). However, as I understand it, the length of the LOR, especially those at the edges of the detector ring, should be less than the diameter of the detector ring. Using the subdivision of each LOR into 29 TOF-bins with a TOF bin width of 169 ps, as mentioned in your article, it appears that the LORs at the ring edges might not be sufficiently long to be divided into 29 TOF-bins. In such cases, do you assign a value of 0 in the sinogram, or is my understanding of the TOF-bins subdivision incorrect? Additionally, how are the TOF-bin indices arranged along an LOR that has been subdivided? Is the bin adjacent to the starting crystal labeled as 0 and the one next to the ending crystal as 28, or is there another arrangement? When generating listmode simulation data using the pyparallelproj framework, I found that some coincidence events with LORs located at the edges have TOF-bin numbers at the ends of the range. My understanding is that the TOF-bin position for a coincidence event should be closer to the starting crystal, but the data generated does not always reflect this.

**Comment by gschramm** [comment]
Hi Kun Tian,

1. `pyparallelproj` is now obsolete. Everything (the complete python API), should be integrated into the `parallelproj` package. See [docs here](https://parallelproj.readthedocs.io/en/stable/) and [github here](https://github.com/gschramm/parallelproj). I wil update the README to redirect to pyparallelproj. The docs also contain a lot of examples visualizing geometries and sinogram - see e.g. [this example](https://parallelproj.readthedocs.io/en/stable/auto_examples/01_pet_geometry/02_run_regular_polygon_pet_sino.html#sphx-glr-auto-examples-01-pet-geometry-02-run-regular-polygon-pet-sino-py)
2. The ordering of LORs into sinograms micked the GE DMI. Different vendors might use different strategies / conventions, but based on the example above, it should be possible that you implement a customized `LOR descriptor` that defines how LORs are ordered into a sinogram, if needed.
3. The choice of the number of TOF bins is "arbitrary". I think if certains TOF bins for the edge LORs are not rejected on the hardware level (which I think they are not for many scanners), then we should still "project" them.
4. The "tof bin number in LM" should be a signed integer that goes from -k ... 0 ... k (when we have 2k + 1 TOF bins). This means that bin "k" is the central TOF bin in the TOF sinogram. Or in other words, if we have a TOF sinogram with 29 TOF bins, [...,0] is the slice that is closest to one detector, [..., 14] is the "central TOF bin slice", [...,28] is the TOF slice closest to the other detector.

**Comment by zjutk** [comment]
Dear Professor Georg Schramm,
Thank you very much for your response to my questions! I will diligently study and explore the content within the parallelproj package. Additionally, I noticed that the PETLORDescriptor's get_lor_coordinates function returns xstart and xend. May I confirm with you that xstart represents the crystal index that first detects the coincidence event, and xend represents the crystal index that detects it subsequently?
Furthermore, as you mentioned, "[...,0] is the slice that is closest to one detector"; does this imply that we assume the tof-bin labeled [...,0] is the one closest to xstart, while the tof-bin labeled [...,28] is closest to xend?
Thank you once again, and I look forward to your reply!

**Comment by gschramm** [comment]
Hi Kun Tian,
`xstart` and `xend`, are the LOR start/end points in "3D real world coordinates" represented by 3 floating point values (not crystal indices. "start" and "end" are not related to the detection time point of the photons, they are "arbritraty" definitions (made by vendors usually) to describe all possible geometrical LORs of a system. In parallelproj TOF sinogram [...,0] are events that hit the "xstart" end of the LOR first, [...,-1] hit "xend" first.

These new `parallelproj` examples should make things more clear:
https://parallelproj.readthedocs.io/en/stable/auto_examples/01_pet_geometry/02_run_regular_polygon_pet_sino.html#sphx-glr-auto-examples-01-pet-geometry-02-run-regular-polygon-pet-sino-py

https://parallelproj.readthedocs.io/en/stable/auto_examples/02_pet_sinogram_projections/01_run_pet_non_tof_sinogram_projector.html#sphx-glr-auto-examples-02-pet-sinogram-projections-01-run-pet-non-tof-sinogram-projector-py

https://parallelproj.readthedocs.io/en/stable/auto_examples/02_pet_sinogram_projections/01_run_pet_non_tof_sinogram_projector.html#sphx-glr-auto-examples-02-pet-sinogram-projections-01-run-pet-non-tof-sinogram-projector-py

Bests,
Georg

**Comment by zjutk** [comment]
Dear Professor Georg Schramm,
Thank you once again for your reply. I will carefully study the examples you provided to resolve my confusion. Wishing you success in your work and happiness in your life!
